# -*- coding: utf-8 -*-
"""Logic-buildingtask-1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JFOiauopLysFlMEnZqoO6bCdfwbUZssa

#
# Logic Building Task – 1
"""

# 1. User Login Check
print("----- 1. User Login Check -----")

correct_username = "admin"
correct_password = "1234"

username = input("Enter username: ")
password = input("Enter password: ")

if username == correct_username and password == correct_password:
    print("Login Successful")
else:
    print("Invalid Credentials")



# 2. Pass / Fail Analyzer
print("\n----- 2. Pass / Fail Analyzer -----")

marks = [45, 78, 90, 33, 60]

pass_count = 0
fail_count = 0

for mark in marks:
    if mark >= 50:
        pass_count += 1
    else:
        fail_count += 1

print("Total Students:", len(marks))
print("Passed Students:", pass_count)
print("Failed Students:", fail_count)



# 3. Simple Data Cleaner
print("\n----- 3. Simple Data Cleaner -----")

names = [" Alice ", "bob", " CHARLIE "]

cleaned_names = []

for name in names:
    cleaned_name = name.strip().lower()  # remove spaces & convert to lowercase
    cleaned_names.append(cleaned_name)

print("Cleaned Names:", cleaned_names)



# 4. Message Length Analyzer
print("\n----- 4. Message Length Analyzer -----")

messages = ["Hi", "Welcome to the platform", "OK"]

for message in messages:
    length = len(message)
    print(f"Message: '{message}' | Length: {length}")

    if length > 10:
        print("⚠ This message is longer than 10 characters")



# 5. Error Message Detector
print("\n----- 5. Error Message Detector -----")

logs = ["INFO", "ERROR", "WARNING", "ERROR"]

error_count = logs.count("ERROR")

print("Total ERROR entries:", error_count)